create_event:
  name: Create event
  description: Add a new calendar event.
  target:
    entity:
      integration: local_calendar
      domain: calendar
  fields:
    summary:
      name: Summary
      description: Acts as the title of the event.
      required: true
      example: "Bowling"
      selector:
        text:
    description:
      name: Description
      description: The description of the event. Optional.
      example: "Birthday bowling"
      selector:
        text:
    start_date_time:
      name: Start time
      description: The date and time the event should start.
      example: "2022-03-22 20:00:00"
      selector:
        text:
    end_date_time:
      name: End time
      description: The date and time the event should end.
      example: "2022-03-22 22:00:00"
      selector:
        text:
    start_date:
      name: Start date
      description: The date the whole day event should start.
      example: "2022-03-10"
      selector:
        text:
    end_date:
      name: End date
      description: The date the whole day event should end.
      example: "2022-03-11"
      selector:
        text:
    rrule:
      name: Recurrence rule
      description: The rule that describes the occurrences of the event.
      example: "FREQ=WEEKLY"
      selector:
        text:
